apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-test-application
  namespace: argocd-test
spec:
  project: default

  source:
    repoURL: https://github.com/melikeyurtoglu/argocd-test.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
